import bcrypt from "bcryptjs";

const data = {
    users:[
        {
            name: 'Ivan',
            email: 'gasevic_ivan@yahoo.com',
            password: bcrypt.hashSync('2605', 8),
            isAdmin: true,
        },
        {
            name: 'Korisnik',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        }
    ],
    products:[
        {
            _id: '1',
            name: 'Intel Core I3 10100F + NVidia GeForce 1650 4GB DDR6',
            category: 'PC',
            image: '/images/pc1.jpg',
            price: '1399.00',
            countInStock: 10,
            brand: 'IT Shop',
            rating: 5,
            numReviews: 22,
            description: '\n\nProcesor: Intel Core i5 10400F 2,9GHz \nMatična ploča: H410M \nGrafika: nVidia GeForce GTX1050TI 4GB \nRam: 8GB DDR4 \nSSD: 256GB \nKućište: Inter-Tech B-02 RGB \nNapajanje: 620W \nOstalo: DP i HDMI. \nGarancija: 24 mj.',
        },
        {
            _id: '2',
            name: 'Intel Pentium G5905 + AMD Radeon RX550 4GB',
            category: 'PC',
            image: '/images/pc2.jpg',
            price: '1097.00',
            countInStock: 20,
            brand: 'IT Shop',
            rating: 4,
            numReviews: 11,
            description: '\nProcesor: Intel Pentium Celeron G5905 3,5 GHz \nMatična ploča: H410M \nGrafika: AMD Radeon RX550 4GB \nRam: 8GB DDR4 \nSSD: M.2 500GB \nKućište: Inter-Tech IT-3306 Cavy \nNapajanje: 620W \nOstalo: DP i HDMI \nGarancija: 24 mj.',
        },   
        {
            _id: '3',
            name: 'Intel Core I3 10100F + NVidia GeForce 1650 4GB DDR6',
            category: 'PC',
            image: '/images/pc3.jpg',
            price: '1399.00',
            countInStock:0,
            brand: 'IT Shop',
            rating: 5,
            numReviews: 24,
            description: '\nProcesor: Intel Core i5 10400F 2,9GHz \nMatična ploča: H410M \nGrafika: nVidia GeForce GTX1050TI 4GB \nRam: 8GB DDR4 \nSSD: 256GB \nKućište: Inter-Tech B-02 RGB \nNapajanje: 620W \nOstalo: DP i HDMI \nGarancija: 24 mj',
        },   
        {
            _id: '4',
            name: 'Intel Core I3 10100F + NVidia GeForce 1650 4GB DDR6',
            category: 'PC',
            image: '/images/pc4.jpg',
            price: '1099.00',
            countInStock: 15,
            brand: 'IT Shop',
            rating: 4.5,
            numReviews: 3,
            description: '\nProcesor: Intel Core i5 10400F 2,9GHz Matična ploča: H410M, Grafika: nVidia GeForce GTX1050TI 4GB Ram: 8GB DDR4 SSD: 256GB Kućište: Inter-Tech B-02 RGB Napajanje: 620W Ostalo: DP i HDMI. Garancija: 24 mj',
        },   
        {
            _id: '5',
            name: 'Intel Core I3 10100F + NVidia GeForce 1650 4GB DDR6',
            category: 'PC',
            image: '/images/pc1.jpg',
            price: '1399.00',
            countInStock: 5,
            brand: 'IT Shop',
            rating: 4,
            numReviews: 14,
            description: 'Procesor: Intel Core i5 10400F 2,9GHz Matična ploča: H410M, Grafika: nVidia GeForce GTX1050TI 4GB Ram: 8GB DDR4 SSD: 256GB Kućište: Inter-Tech B-02 RGB Napajanje: 620W Ostalo: DP i HDMI. Garancija: 24 mj',
        },   
        {
            _id: '6',
            name: 'Intel Core I3 10100F + NVidia GeForce 1650 4GB DDR6',
            category: 'PC',
            image: '/images/pc1.jpg',
            price: '1399.60',
            countInStock: 12,
            brand: 'IT Shop',
            rating: 3.5,
            numReviews: 18,
            description: 'Procesor: Intel Core i5 10400F 2,9GHz Matična ploča: H410M, Grafika: nVidia GeForce GTX1050TI 4GB Ram: 8GB DDR4 SSD: 256GB Kućište: Inter-Tech B-02 RGB Napajanje: 620W Ostalo: DP i HDMI. Garancija: 24 mj',
        },   
    ],
};

export default data;